parameters:
    team_velocity: 47.0
    velocity_explanation: "basé sur dispo de l'équipe. 3 personnes , 2 dev back, 1 dev front.  + 1/3 du sprint pour lead dev (5J)\n\nsprint de 15 jours. soit 3 * 15 + 5 =  50. mais comme agilité et pas mal de réunion sprint j'enleve 1 jour par personne d'insdispo pour dev."
